### ISSUE TITLE
PID to be tuned

### ISSUE THREAD

**Issue by psnx** [psnx/CarND-Capstone#6]
PID has to be tuned for yaw and speed control! More Kd would help a lot

**Comment by renlei1982** [comment]
Mission accepted.

2017年9月29日 下午1:05，"psnx" <notifications@github.com>写道：

Assigned #6 <https://github.com/psnx/CarND-Capstone/issues/6> to @renlei1982
<https://github.com/renlei1982>.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/psnx/CarND-Capstone/issues/6#event-1272294336>, or mute
the thread

**Comment by psnx** [comment]
Good enough for 1st submission
